MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  command: talismans
  aliases: [talisman, amuleto, amuletos]
  admin-permission: 'talismans.admin'

Messages:
  invalid-amount: '&cO valor inserido é inválido!'
  insufficient-fragments: '&cVocê não possui fragmentos de talismã suficientes! ({has}/{need})'
  choose-amount:
    - ''
    - '&7Digite no chat quantos fragmentos deseja retirar!'
    - '&7Para retirar o máximo possível digite ''&f*&7''!'
    - ''

Fragment-Item:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk0YWJhNDg4MzFjNTU4MWIwYzRkZDE0MjZhNzk0MjczMjkwZjY2MDAxYmNkMWMzYjdhMDExMzJiMjEzYWYwMCJ9fX0=
  name: '&aFragmento de Talismã &7(Botão direito)'
  lore:
    - '&7Ative esse item para &fcriar'
    - '&7qualquer &ftalismã&7!'